include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude:
    - lib/l10n/*
    - lib/generated/*
    - lib/firebase_options.dart
linter:
  rules:
    public_member_api_docs: false
