// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3h-UfR7Kx-yJdPK7pqMXPrNfjiBG9jQ',
    appId: '1:1067961968697:web:086c308d584b28477185e8',
    messagingSenderId: '1067961968697',
    projectId: 'fir-workshop-8801d',
    authDomain: 'fir-workshop-8801d.firebaseapp.com',
    storageBucket: 'fir-workshop-8801d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3A_gdywaVyE-n_u0CwiOqMHDELfIegMg',
    appId: '1:1067961968697:android:0d2ebcb2f96252477185e8',
    messagingSenderId: '1067961968697',
    projectId: 'fir-workshop-8801d',
    storageBucket: 'fir-workshop-8801d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvoI92vO6t1VI1-gz8uqWWDJ6T1rT7WJ0',
    appId: '1:1067961968697:ios:ef7896af72739f1b7185e8',
    messagingSenderId: '1067961968697',
    projectId: 'fir-workshop-8801d',
    storageBucket: 'fir-workshop-8801d.appspot.com',
    iosClientId:
        '1067961968697-hdapv6t87rfk00hvf1b2csapubr9h957.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase-workshop',
  );
}
